title: Jambot Blog
email: jamie@example.com
description: >
  A minimal Jekyll blog for Jambot using the hacker theme.

baseurl: "/jambot-blog"
url: "https://jamieclaw.github.io"

author:
  name: Jamie Phan
  email: jamie@example.com

markdown: kramdown
theme: jekyll-theme-hacker

plugins:
  - jekyll-feed

# GitHub Pages
github:
  is_project_page: true
